### ISSUE TITLE
Relative Links Bug in Contest Description

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#242]
Steps:
- Go to https://tlx.toki.id/contests/troc-9-div-2
- From the Contest Menu, go to anywhere else (e.g. Problems)
- Go back to Overview
- Click on the TROC-9 Div 1 link
- It brings you to https://tlx.toki.id/contests/troc-9-div-2/troc-9-div-1 instead of https://tlx.toki.id/contests/troc-9-div-1

This also happens to all other TROC contests description

**Comment by jonathanirvings** [comment]
Seems like this is due to the browser is on `https://tlx.toki.id/contests/troc-9-div-2/` (notice the backslash at the end, instead of `https://tlx.toki.id/contests/troc-9-div-2`) after going to anywhere else (including if you click the "Overview" button).

Therefore, clicking the TROC-9 Div 1 link (which is href-ed to `troc-9-div1`) redirects to `https://tlx.toki.id/contests/troc-9-div-2/troc-9-div-1`, while clicking it from `https://tlx.toki.id/contests/troc-9-div-2` (without the backslash at the end) redirects to `https://tlx.toki.id/contests/troc-9-div-1`, which is intended.

**Comment by jonathanirvings** [comment]
Created #243 so that the contest will always be visited with a backslash at the end. Creating the description from this page will set the href to `../troc-9-div-1` instead.

**Comment by fushar** [comment]
I don't think it is Judgels's bug. This is how URLs work. This is because the link is relative.

We can't control whether user/browser/any other agent will append trailing backslash because it is still a valid URL.

Solution: just use absolute link in description.

**Comment by prabowo02** [comment]
Currently we are unable to use absolute link, because it will be automatically converted to relative link again

**Comment by jonathanirvings** [comment]
Seems like TinyMCE automatically converts absolute URL to relative URL
https://stackoverflow.com/questions/5196205/disable-tinymce-absolute-to-relative-url-conversions

**Comment by fushar** [comment]
OK, reopening this.
